server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assembled_model?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: letere
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver